version: "3.8"

services:
  app:
    build: .
    ports:
      - "8082:8000"
    networks:
      - bff-network
    depends_on:
      - client_portfolio

  client_portfolio:
    image: mongo:latest
    ports:
      - "27008:27017"
    networks:
      - bff-network
    volumes:
      - mongodb_data:/data/db

  dbseed:
    build: ./dbseed
    networks:
      - bff-network
    depends_on:
      - client_portfolio

volumes:
  mongodb_data:

networks:
  bff-network:
    external: true
